apiVersion: v1
kind: Template
labels:
  app: csdexporter
  template: csdexporter-buildconfig
metadata:
  annotations:
    description: Cassandra exporter - BuildConfig
      see https://github.com/Worteks/docker-csdexporter
    iconClass: icon-openshift
    openshift.io/display-name: Cassandra Exporter
    openshift.io/provider-display-name: Worteks
    openshift.io/support-url: https://www.worteks.com
    tags: csdexporter
  name: csdexporter-buildconfig
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Pingdom Cassandra Exporter images
    labels:
      name: csdexporter-${FRONTNAME}-${CASSANDRA_EXPORTER_REPOSITORY_REF}
    name: csdexporter-${FRONTNAME}-${CASSANDRA_EXPORTER_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 300m
        memory: 768Mi
    source:
      contextDir: /
      git:
        uri: ${CASSANDRA_EXPORTER_REPOSITORY_URL}
        ref: "${CASSANDRA_EXPORTER_REPOSITORY_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
        from:
          kind: ImageStreamTag
          name: ${JAVA_IMAGESTREAM_TAG}
    output:
      to:
        kind: ImageStreamTag
        name: csdexporter-${FRONTNAME}:${CASSANDRA_EXPORTER_REPOSITORY_REF}
    triggers:
    - type: ConfigChange
parameters:
- name: CASSANDRA_EXPORTER_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: CASSANDRA_EXPORTER_REPOSITORY_URL
  description: The URL of the repository with your cassandra exporter Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-csdexporter.git
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: JAVA_IMAGESTREAM_TAG
  description: Set this to Java ImageStream tag serving as base for Cassandra BuildConfig
  displayName: Java ImageStream Tag
  required: true
  value: java-wsweet:master
