apiVersion: v1
kind: Template
labels:
  app: csdexporter
  template: csdexporter-imagestream
metadata:
  annotations:
    description: Cassandra exporter - ImageStream
      see https://github.com/Worteks/docker-csdexporter
    iconClass: icon-openshift
    openshift.io/display-name: Cassandra Exporter
    openshift.io/provider-display-name: Worteks
    openshift.io/support-url: https://www.worteks.com
    tags: csdexporter
  name: csdexporter-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Cassandra Exporter image
    name: csdexporter-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
